
vec3 rgb_to_hsv(vec3 c) {
    vec4 K = vec4(0.0, -1.0 / 3.0, 2.0 / 3.0, -1.0);
    vec4 p = mix(vec4(c.bg, K.wz), vec4(c.gb, K.xy), step(c.b, c.g));
    vec4 q = mix(vec4(p.xyw, c.r), vec4(c.r, p.yzx), step(p.x, c.r));

    float d = q.x - min(q.w, q.y);
    float e = 1.0e-10;
    return vec3(abs(q.z + (q.w - q.y) / (6.0 * d + e)), d / (q.x + e), q.x);
}

vec3 hsv_to_rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0 / 3.0, 1.0 / 3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}

vec4 hue_rotate(vec4 c, float value) {
	return vec4(
		hsv_to_rgb(rgb_to_hsv(c.rgb) + vec3(value, 0.0, 0.0)),
		c.a
	);
}

vec4 blend_mix(in vec4 p_dst, in vec4 p_src) {
	return vec4(
		mix(p_dst.rgb, p_src.rgb, p_src.a),
		p_src.a + p_dst.a * (1 - p_src.a)
	);
}

