#!/bin/sh

cd gdex-doc-gen
python3 -m venv .env
. .env/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
./generator.py -project_name "Godot RmlUi" -src_folder ../../doc_classes -dst_folder ../
deactivate